#
# Supported ECR image releases. Fedora-based, custom Linux.
#
# - https://gallery.ecr.aws/lambda/nodejs
# - https://github.com/aws/aws-lambda-base-images
# 
FROM public.ecr.aws/lambda/nodejs:20
  
RUN dnf install -y gzip tar
